// src/lib/indian-vcs.ts
// Curated database of major Indian VC funds with their portfolio page URLs
// This helps bootstrap the tool with known fund URLs

export interface KnownVCFund {
  name: string;
  website: string;
  portfolioPage?: string;
  focus: string[];
  stage: string[];
  aum?: string;
  location: string;
  description: string;
  notable?: string[];
}

export const KNOWN_INDIAN_VCS: KnownVCFund[] = [
  {
    name: "Sequoia Capital India (Peak XV)",
    website: "https://www.peakxv.com",
    portfolioPage: "https://www.peakxv.com/companies/",
    focus: ["Consumer", "SaaS", "Fintech", "Healthcare", "Deep Tech"],
    stage: ["Seed", "Series A", "Series B", "Growth"],
    aum: "$2.8B+",
    location: "Bengaluru",
    description: "India's largest venture fund, formerly Sequoia Capital India",
    notable: ["Byju's", "Razorpay", "Meesho", "Groww", "OYO"],
  },
  {
    name: "Accel India",
    website: "https://www.accel.com/locations/india",
    portfolioPage: "https://www.accel.com/companies",
    focus: ["SaaS", "Consumer", "Fintech", "B2B"],
    stage: ["Seed", "Series A", "Series B"],
    aum: "$1B+",
    location: "Bengaluru",
    description: "Early-stage VC with strong SaaS and consumer portfolio",
    notable: ["Flipkart", "Freshworks", "BrowserStack", "Swiggy", "Urban Company"],
  },
  {
    name: "Blume Ventures",
    website: "https://blume.vc",
    portfolioPage: "https://blume.vc/portfolio/",
    focus: ["Deep Tech", "Consumer", "SaaS", "Fintech"],
    stage: ["Pre-seed", "Seed", "Series A"],
    aum: "$400M+",
    location: "Mumbai / Bengaluru",
    description: "India's leading seed-stage VC fund",
    notable: ["Unacademy", "Slice", "Dunzo", "GreyOrange", "Purplle"],
  },
  {
    name: "Nexus Venture Partners",
    website: "https://www.nexusvp.com",
    portfolioPage: "https://www.nexusvp.com/portfolio",
    focus: ["Enterprise SaaS", "Consumer", "Fintech"],
    stage: ["Series A", "Series B", "Growth"],
    aum: "$1.5B+",
    location: "Bengaluru",
    description: "Early and growth stage VC with cross-border portfolio",
    notable: ["Delhivery", "Snapdeal", "Druva", "Craftsvilla"],
  },
  {
    name: "Kalaari Capital",
    website: "https://www.kalaari.com",
    portfolioPage: "https://www.kalaari.com/portfolio/",
    focus: ["Consumer", "SaaS", "Healthtech", "Edtech"],
    stage: ["Seed", "Series A", "Series B"],
    aum: "$650M+",
    location: "Bengaluru",
    description: "Early-stage VC focused on Indian innovation",
    notable: ["Dream11", "Cure.fit", "Myntra", "Urban Ladder"],
  },
  {
    name: "Matrix Partners India",
    website: "https://www.matrixpartners.in",
    portfolioPage: "https://www.matrixpartners.in/portfolio",
    focus: ["Consumer", "SaaS", "Fintech"],
    stage: ["Seed", "Series A", "Series B"],
    aum: "$1B+",
    location: "Bengaluru / Mumbai",
    description: "Multi-stage VC with strong consumer and fintech focus",
    notable: ["Ola", "Razorpay", "Dailyhunt", "County9", "Mswipe"],
  },
  {
    name: "SAIF Partners (Elevation Capital)",
    website: "https://elevationcapital.com",
    portfolioPage: "https://elevationcapital.com/portfolio",
    focus: ["Consumer", "Fintech", "SaaS", "Healthcare"],
    stage: ["Series A", "Series B", "Growth"],
    aum: "$1.5B+",
    location: "Gurugram",
    description: "Growth-stage VC, rebranded from SAIF Partners",
    notable: ["Paytm", "MakeMyTrip", "Meesho", "ShareChat", "Urban Company"],
  },
  {
    name: "Lightspeed India",
    website: "https://lsvp.com/teams/india/",
    portfolioPage: "https://lsvp.com/companies/",
    focus: ["Consumer", "Enterprise", "Fintech", "Clean Energy"],
    stage: ["Seed", "Series A", "Growth"],
    aum: "$1B+",
    location: "Bengaluru",
    description: "Global VC with strong India portfolio",
    notable: ["OYO", "Byju's", "Udaan", "Shaadi.com", "Darwinbox"],
  },
  {
    name: "Chiratae Ventures",
    website: "https://www.chiratae.com",
    portfolioPage: "https://www.chiratae.com/portfolio",
    focus: ["Deep Tech", "Consumer", "Healthcare", "B2B"],
    stage: ["Seed", "Series A", "Series B"],
    aum: "$500M+",
    location: "Bengaluru",
    description: "Formerly IDG Ventures, focused on technology companies",
    notable: ["PolicyBazaar", "FirstCry", "Lenskart", "Myntra"],
  },
  {
    name: "3one4 Capital",
    website: "https://3one4.com",
    portfolioPage: "https://3one4.com/portfolio",
    focus: ["SaaS", "Deep Tech", "Consumer", "Climate"],
    stage: ["Pre-seed", "Seed", "Series A"],
    aum: "$400M+",
    location: "Bengaluru",
    description: "Founder-friendly early-stage fund with deep tech focus",
    notable: ["Darwinbox", "Licious", "Open Financial", "Setu", "Runr"],
  },
  {
    name: "India Quotient",
    website: "https://indiaquotient.in",
    portfolioPage: "https://indiaquotient.in/portfolio/",
    focus: ["Consumer", "Vernacular", "Rural Tech", "Fintech"],
    stage: ["Pre-seed", "Seed"],
    aum: "$150M+",
    location: "Mumbai",
    description: "Seed fund focused on building for Bharat",
    notable: ["ShareChat", "Agrostar", "Classplus", "BetterPlace"],
  },
  {
    name: "Stellaris Venture Partners",
    website: "https://stellarisvp.com",
    portfolioPage: "https://stellarisvp.com/portfolio",
    focus: ["SaaS", "Consumer", "Fintech"],
    stage: ["Pre-seed", "Seed", "Series A"],
    aum: "$225M+",
    location: "Bengaluru",
    description: "Early-stage fund with strong engineering-led founders",
    notable: ["Pixxel", "Jar", "Animall", "Bijnis", "LenDenClub"],
  },
  {
    name: "Fireside Ventures",
    website: "https://firesideventures.com",
    portfolioPage: "https://firesideventures.com/portfolio/",
    focus: ["Consumer Brands", "D2C"],
    stage: ["Seed", "Series A"],
    aum: "$200M+",
    location: "Bengaluru",
    description: "India's leading consumer brands fund",
    notable: ["Mamaearth", "Boat", "Paper Boat", "Yoga Bar", "The Sleep Company"],
  },
  {
    name: "Waterbridge Ventures",
    website: "https://www.waterbridgevc.com",
    portfolioPage: "https://www.waterbridgevc.com/portfolio",
    focus: ["Consumer", "Fintech", "SaaS"],
    stage: ["Pre-seed", "Seed"],
    aum: "$100M+",
    location: "Mumbai",
    description: "Founder-focused seed fund",
    notable: ["Fashinza", "Infra.Market", "Eduvanz"],
  },
  {
    name: "Omnivore Partners",
    website: "https://omnivore.vc",
    portfolioPage: "https://omnivore.vc/portfolio/",
    focus: ["Agri-tech", "Food Tech", "Rural Tech", "Climate"],
    stage: ["Seed", "Series A"],
    aum: "$150M+",
    location: "Mumbai",
    description: "India's first agrifood tech focused VC",
    notable: ["WayCool", "Agrostar", "Stellapps", "Intello Labs"],
  },
  {
    name: "pi Ventures",
    website: "https://www.piventures.in",
    portfolioPage: "https://www.piventures.in/portfolio",
    focus: ["AI/ML", "Deep Tech", "IoT"],
    stage: ["Seed", "Series A"],
    aum: "$75M+",
    location: "Bengaluru",
    description: "Deep tech VC focused on AI and machine learning",
    notable: ["Niramai", "Detect Technologies", "Fluid AI", "SigTuple"],
  },
  {
    name: "Venture Highway",
    website: "https://www.venturehighway.vc",
    portfolioPage: "https://www.venturehighway.vc/portfolio",
    focus: ["Consumer", "SaaS", "Gaming"],
    stage: ["Seed", "Series A"],
    aum: "$100M+",
    location: "Gurugram",
    description: "Early-stage fund with a portfolio-as-a-community approach",
    notable: ["Snapdeal", "Spring Health", "Meesho", "Khatabook"],
  },
  {
    name: "Antler India",
    website: "https://www.antler.co/india",
    portfolioPage: "https://www.antler.co/portfolio",
    focus: ["Cross-sector", "Pre-seed"],
    stage: ["Pre-seed"],
    aum: "$50M+",
    location: "Bengaluru",
    description: "Global company builder and early-stage VC",
    notable: [],
  },
  {
    name: "Fundamentum Partnership",
    website: "https://fundamentum.in",
    portfolioPage: "https://fundamentum.in/portfolio",
    focus: ["Consumer", "SaaS", "Enterprise"],
    stage: ["Series B", "Series C", "Growth"],
    aum: "$200M+",
    location: "Gurugram",
    description: "Growth-stage VC co-founded by Nandan Nilekani",
    notable: ["Khatabook", "Classplus", "ElasticRun", "Healthifyme"],
  },
  {
    name: "Z47 (formerly known as Eight Roads Ventures India)",
    website: "https://www.z47.com",
    portfolioPage: "https://www.z47.com/portfolio",
    focus: ["Consumer", "Fintech", "Healthcare"],
    stage: ["Series A", "Series B", "Growth"],
    aum: "$1B+",
    location: "Mumbai",
    description: "Fidelity's global VC arm",
    notable: ["Lenskart", "PharmEasy", "BigBasket", "Vedantu"],
  },
];

export function searchKnownFunds(query: string): KnownVCFund[] {
  const q = query.toLowerCase();
  return KNOWN_INDIAN_VCS.filter(
    f => f.name.toLowerCase().includes(q) || 
         f.website.toLowerCase().includes(q) ||
         f.focus.some(s => s.toLowerCase().includes(q))
  );
}
